### ISSUE TITLE
Does not use output path given in .inp file

### ISSUE THREAD

**Issue by danrhouck** [SNL-WaterPower/CACTUS#25]
This is a little thing, but it seems to me that the output files are always placed one level above the folders for the airfoil data and geometry. I haven't done thorough testing, but that's where they always go for me. Would be nice if they actually went in the assigned folder.

**Comment by whophil** [comment]
Right now it is hard-coded to put the files in `./output`, which is relative to the path where you are executing CACTUS from. That is the behavior I see on Mac. Do you see different behavior on Windows?

**Comment by whophil** [comment]
The path you supply in ConfigOutputs -> OutputPath is taken relative to the path you are executing CACTUS from. I see the correct behavior on Mac. Can you please paste your `.in` file and the command you used to execute?

**Comment by danrhouck** [comment]
From the .in file:
```
&ConfigOutputs

    OutputPath = '../mine/V27TestOutput'
```
Run command:
```
drhouck@S1023207 MINGW64 ~/cactus/build
$ ./cactus ../mine/V27.inp
```

**Comment by whophil** [comment]
As stated, `OutputPath`, (and all other paths included in the `.in` file) are relative to the _working directory you executed CACTUS from_, not relative to the input file itself. I don't know what your full directory tree looks like, but it seems that output files are being put in the right place.

**Comment by danrhouck** [comment]
Tree is as follows:
CACTUS>build>cactus.exe
CACTUS>mine>OutputFolder

I think I have the paths correct, but I'm not certain. This is new to me.

**Comment by danrhouck** [comment]
My fault. The path needs a final '/' at the end and I did not include that originally. Without the last slash, it ignores the last part of the path and puts it one folder up.
