### ISSUE TITLE
CACTUS GUST SIMULATION

### ISSUE THREAD

**Issue by sakibsadman7** [SNL-WaterPower/CACTUS#29]
Hi everyone,

I was wondering how do one correctly model the gust simulation correctly in CACTUS? I have played around with the igust, gustamp, gusttime, gustX0 parameters but I get no difference in the result. Would be grateful for some tips and suggestions!

Best Wishes,
Sadman Sakib
The University of Texas at Dallas

**Comment by xflow-ian** [comment]
I have also been having issues with the gust simulation. By monitoring the `fieldData `output, I am able to observe that setting `igust = 1` overrides the free stream to be uniform, even when `slex ` is non zero. I have tried a variety of physically relvant values of `gustamp`, `gusttime`, and `gustX0 `, but am not able to observe the gust in the free stream or induced velocity fields.

**Comment by whophil** [comment]
There appears to be a bug in the implementation of the gust velocity. See the snippet below.

https://github.com/SNL-WaterPower/CACTUS/blob/4e7db1112ffa34f7e62d154e12eaa83e342d63c3/src/CalcFreestream.f95#L20-L40

Here, the gust velocity is clearly being overwritten by the shear profile when really they should be added together.

As with many other things in CACTUS, the gust module is quite immature. It only supports the "EOG" gust. If you intend on modeling other DLCs, you'd likely want to develop a more modular way to specify the inflow, i.e., `U(x,y,z,t)`

**Comment by whophil** [comment]
Actually, that's not quite right, I didn't see the `return`. Let me look into this a bit more.

**Comment by whophil** [comment]
It looks like shear is ignored when `igust = 1`.

After some experimentation, I was able to see gust effects in the exported field data. Can you share the gust parameters you are using?

**Comment by xflow-ian** [comment]
Glad to hear it is working for you! My gust parameters were  `gustamp = 2`, `gusttime = 0.5`, `gustX0 = -5`. The gust starting location, `gustX0`, was chosen to be upstream of the rotor and my `gusttime ` corresponded to half a rotation of the turbine. The nominal free stream velocity was 8 m/s so I would have expected a 2 m/s gust to be noticeable. 

For my field data, I was recording 20 points vertically spaced at the X-Z position 2 diameters upstream of the rotor.

**Comment by xflow-ian** [comment]
Could you share your parameters so I can try to recreate them on my machine?

**Comment by whophil** [comment]
I've attached a modified `TestCase1/TestHAWT.in` which applies a gust and also samples field data every timestep at the `(0, 0, 0)` using the Probe feature. 

Here is a plot of `Ufs/Uinf` from the probe data.

![image](https://user-images.githubusercontent.com/2186528/90645262-fa8b7480-e1f2-11ea-8827-02a8f294c1c6.png)

[TestCaseGust.zip](https://github.com/SNL-WaterPower/CACTUS/files/5096996/TestCaseGust.zip)
Unzip this into `[CACTUS source]/test/` to run.

**Comment by xflow-ian** [comment]
Thanks for sharing this example. I was able to replicate it on my machine. Additionally, I was able to change the gust parameters and have the gust profile change as expected.

**Comment by whophil** [comment]
Great! The confusing part for me was the `gusttime` parameter, which needed to be much longer than what I had originally set when I was just messing around. Closing this issue.
