### ISSUE TITLE
Open-source this repo

### ISSUE THREAD

**Issue by petebachant** [SNL-WaterPower/CACTUS#4]
We (@whophil @kmruehl @wosnik @nearyvs @awilmurph) were discussing this a bit via email. If export control regulations will allow, it would be helpful to make this repo public. Some advantages include:
- Can use free continuous integration (CI) tools for testing, e.g., Travis CI (#2) and AppVeyor (#3)
- Users can file bug reports and feature requests here
- Users that aren't necessarily involved with the project can submit pull requests to improve the code

**Comment by kmruehl** [comment]
Both repos are now public.
