### ISSUE TITLE
Modify Computational Domain

### ISSUE THREAD

**Issue by sakibsadman7** [SNL-WaterPower/CACTUS#41]
Hi,

I was wondering is it possible to modify the computational domain in CACTUS to match a wind tunnel test section? What we are trying to do is to capture the effect of bounding walls on the rotor power and loads (blockage effect). Any suggestions regarding the issue will be greatly appreciated.

Best
Sadman Sakib

**Comment by whophil** [comment]
@sakibsadman7 yes, this can be done. The image below shows such a setup.
![image](https://user-images.githubusercontent.com/2186528/110148809-84b7b680-7d9a-11eb-84e7-c0239bc8018a.png)

Please refer to section 3.4 in the User Manual.
https://github.com/SNL-WaterPower/CACTUS/blob/dev/doc/user-guide/tex/User%20Guide.pdf

**Comment by sakibsadman7** [comment]
Thank you so much, this was really helpful!
