### ISSUE TITLE
Failed install in Linux

### ISSUE THREAD

**Issue by Jingna416** [SNL-WaterPower/CACTUS#45]
Hello everyone,

I am compiling in the linux platform. With make command, I got this error:

[100%] Linking Fortran executable ../bin/cactus
/usr/bin/ld: CMakeFiles/cactus.dir/src/WSolnSetup.f95.o: in function `wsolnsetup_':
WSolnSetup.f95:(.text+0x77a): undefined reference to `dgesv_'
/usr/bin/ld: CMakeFiles/cactus.dir/src/mod/wallsystem.f95.o: in function `__wallsystem_MOD_invert_influence_matrix':
wallsystem.f95:(.text+0x1438): undefined reference to `dgesv_'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/cactus.dir/build.make:1029: ../bin/cactus] Error 1
make[1]: *** [CMakeFiles/Makefile2:76: CMakeFiles/cactus.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

Any help would be appreciated.

Best,
Jingna

**Comment by whophil** [comment]
Seems like the compile process cannot find a BLAS library. Do you have one installed? If not, try

apt install libopenblas-dev

Or the equivalent for your Linux distro

**Comment by Jingna416** [comment]
> Seems like the compile process cannot find a BLAS library. Do you have one installed? If not, try
> 
> apt install libopenblas-dev
> 
> Or the equivalent for your Linux distro

Hi Phil,

Thank you very much for your reply. I did $sudo apt-get install libblas-dev checkinstall    and
                                                                   $sudo apt-get install liblapack-dev checkinstall

This made me move forwards. Thanks for the hint.

But I still got a line of "fatal: bad revision 'HEAD'" when I use cmake and make. I just copy and paste the zip file and extract it into my folder instead of using git clone. Do I miss something in between?

Thank you for your patience.

Best wishes,
Jingna

**Comment by whophil** [comment]
This is a flaw in the build system.

Right now it requires that you've cloned the repo, and that you have git installed on your machine. This is done so that the executable is traceable to a git commit. Unfortunately, there is currently no fallback if getting the git commit breaks for any reason.

**Comment by Jingna416** [comment]
> This is a flaw in the build system.
> 
> Right now it requires that you've cloned the repo, and that you have git installed on your machine. This is done so that the executable is traceable to a git commit. Unfortunately, there is currently no fallback if getting the git commit breaks for any reason.

Hi Phil,

Thanks a lot for your thorough explanation. I recompile with the cloned file. Now it runs very well. Thanks again for your kind reply!

Cheers,
Jingna
