### ISSUE TITLE
Not compiling with Intel Fortran

### ISSUE THREAD

**Issue by NilsBForze** [SNL-WaterPower/CACTUS#47]
Dear CACTUS-Community,

I cloned the repo and followed the compilation instructions. Unfortunately, I receive the following error when executing make:

![image](https://user-images.githubusercontent.com/16734375/124931811-d9966280-e002-11eb-8cb4-00870bc66c2f.png)

Has someone suggestions on how to fix the problem? What additional information do you require to help me? I am a Mac user with intel compilers installed.

Thank you very much in advance

Nils

**Comment by whophil** [comment]
Hi Nils, can you verify that airfoil.f95 actually contains code? Also, please share the entirety of your cmake output.

**Comment by NilsBForze** [comment]
Dear Phil,

thank you very much for the quick reply. Yes airfoil.f95 does contain code.

Here attached the CMakeOutput.log file. 

[CMakeOutput.log](https://github.com/SNL-WaterPower/CACTUS/files/6790237/CMakeOutput.log)

Regards

Nils

**Comment by NilsBForze** [comment]
I solved my problem by switching to the GNU compiler. It might be worth investigating whether the current Cmake configuration is still compatible with the newest intel Fortran compiler.

**Comment by whophil** [comment]
> I solved my problem by switching to the GNU compiler. It might be worth investigating whether the current Cmake configuration is still compatible with the newest intel Fortran compiler.

Sorry @NilsBForze , just had time to look at this. I just tested and have the same problem with Intel Fortran. Re-opening this issue for tracking.

**Comment by whophil** [comment]
Should be fixed with https://github.com/SNL-WaterPower/CACTUS/pull/48, but that PR needs testing
