### ISSUE TITLE
Is my rotor going forwards AND backwards?

### ISSUE THREAD

**Issue by danrhouck** [SNL-WaterPower/CACTUS#49]
This has never happened before. How is this possible?
It looks like, approximately, every rev starting around rev 15 has one timestep that reads as rev 33. Around rev 32 or 33, it gets more mixed up with an additional rev reading out for some timesteps. It's set to start saving data at rev 35. It's saving over old data from a run that failed, but that's never been an issue before. 
![image](https://user-images.githubusercontent.com/67019759/128421595-dc5a2a7a-0b5b-4b15-b0b2-f6bdb2fd766c.png)

**Comment by whophil** [comment]
~Do you have two or more runs saving to the same file simulataneously? It is hard to see how you would get those timestep numbers otherwise.~

EDIT: Actually that makes no sense. Is the screenshot you posted of the output of the executable stdout, or the actual file contents?

**Comment by danrhouck** [comment]
It's the output of the executable. I looked in the output folder for field data and they're out of order too. Specifically, the file numbers are in order, but the dates/times on which they're saved go back in forth in time. More specifically, even though I'm saving over some old data from a previous run that failed, the files that are out of order are all the new ones from the current run.

**Comment by danrhouck** [comment]
Figured it out. This is the danger of "disowning" a process to make it resistant to some failures. I do in fact have more than one simulation outputting data to the same folder. I just completely forgot that I did that. User error all the way.
