### ISSUE TITLE
Issues with the Geometry File

### ISSUE THREAD

**Issue by Meghas30** [SNL-WaterPower/CACTUS#51]
Hi Everyone, I am new to coding and doing my best to learn it. I am having issues understanding the Cactus geometry file. I want to simulate a straight-bladed rotor with three blades (Like RM2 tow-tank Experiment Sandia Lab). I don´t know how to calculate the blade unit tangent vectors for my simple geometry to modify the cactus geometry file. 
I would appreciate it if you can provide any document to understand this geometry file. So far I have the Cactus and the Cactus development Manual Only.
Thank you.
@whophil

**Comment by Satyamshk2** [comment]
![Unit vector](https://user-images.githubusercontent.com/96062229/150117085-7a937de3-bb21-4ae9-9565-a093ccdd1b42.jpeg)

**Comment by Satyamshk2** [comment]
Here, you can say (X, Y, Z) =(2, -4, 1)  are the coordinates at elements ends.

**Comment by Meghas30** [comment]
@Satyamshk2 Thank you
