### ISSUE TITLE
Fixed preset blade pitch angle 

### ISSUE THREAD

**Issue by Satyamshk2** [SNL-WaterPower/CACTUS#53]
Hello,
 I am working on a straight-bladed cross-flow turbine (NACA0015) with a solidity of 0.15. I have the experimental data and am trying to simulate the same in CACTUS. I have the data for different pitch angles and want to simulate the same in the cactus. I am modifying the blade pitch angle by changing the mount point ratio (eta) in the code during geometry creation (**the quote**). My cactus results are not in agreement at all with the experiment data on all the pitch angles. I could not find a way to give a fixed preset blade pitch angle in the code other than changing the **mount point** for a VAWT.

"**A forward shift of mount-point from the centre of the chord towards the leading edge corresponds to an effective toe-in pitch

change of β = tan^-1[x/R]**"

where x is the distance between the two shifting points.
Could you please tell me the ways I can provide blade pitch angle in the code for a Straight-bladed VAWT?
![image](https://user-images.githubusercontent.com/96062229/153003847-9fd6d66d-fe1f-408b-86aa-7a3e52f7e8bb.png)

**Comment by Satyamshk2** [comment]
@whophil @jcokemurray @kmruehl @petebachant  Could you please help me here?

**Comment by petebachant** [comment]
Hi @Satyamshk2, sorry but I've never done this in CACTUS, so I'm not sure if it's possible in the config.

**Comment by Satyamshk2** [comment]
> Hi @Satyamshk2, sorry but I've never done this in CACTUS, so I'm not sure if it's possible in the config.

Thank you

**Comment by whophil** [comment]
Hi @Satyamshk2 , I'm not sure I understand your question. How are you building the geometry input file? With the parameters described in section 3.2 of the [user guide](https://github.com/SNL-WaterPower/CACTUS/blob/dev/doc/user-guide/tex/User%20Guide.pdf), you should have the flexibility to build whatever geometry you see fit.

**Comment by Satyamshk2** [comment]
> Hi @Satyamshk2 , I'm not sure I understand your question. How are you building the geometry input file? With the parameters described in section 3.2 of the [user guide](https://github.com/SNL-WaterPower/CACTUS/blob/dev/doc/user-guide/tex/User%20Guide.pdf), you should have the flexibility to build whatever geometry you see fit.

Thanks for your reply.
I have the flexibility to build whatever geometry I want through the Matlab files. My question was about a fixed preset blade pitch angle. How do you provide the blade pitch angle in the CACTUS code for a VAWT? 

Geometry Creation Code 

clear
close all
%GEOMETRY FOR URV MODEL
% Creates test VAWT geometry file

% Add geom creation scripts to path
path(path,'E:/Satyam/CACTUS-dev/CreateGeom');

% Params
R=1.23031;            % Center radius (ft)
%H=2.46063            %Height of the turbine
%RefAR=H*D/R^2             %Frontal area normalized by R^2
HR=2.46063/1.23031;           % Height to radius ratio 
CRr=0.32;        % Root chord to radius
**eta=.5;**  % **Blade mount point ratio (mount point behind leading edge as a fraction of chord)**
NBlade=3;
NBElem=16;
NStrut=6;       % number of struts
NSElem=16;
CRs=CRr;        % strut chord to radius
TCs=0.15;        % strut thickness to chord

% Output filename
FN='TestVAWT.geom';

% Plot data?
PlotTurbine=1;

% Convert
dToR=pi/180;

% Create basic parabolic blade VAWT
Type='VAWT';
BShape=0;
T=CreateTurbine(NBlade,NBElem,NStrut,NSElem,R,[],[],[],Type,1,CRr,HR,eta,BShape,CRs,TCs);

% Write geom file
WriteTurbineGeom(FN,T);

% Plot if desired
if PlotTurbine
    
    % Plot animated turbine rotation
    XLim=[-4,4];
    YLim=[-2,4];
    ZLim=[-4,4];
    
    % Plot controls
    PlotVec=1;
    SFVec=.5;
    Trans=.5;
    
    hf=figure(1);
    set(hf,'Position',[303   124   956   610]) 
    set(gca,'Position',[5.2743e-002  5.1245e-002  8.9979e-001  8.8141e-001])
    set(gca,'CameraPosition',[-52.1999   30.4749   62.2119])
    set(gca,'CameraUpVector',[1.8643e-001  9.7433e-001 -1.2615e-001])
    set(gca,'CameraViewAngle',6.3060e+000)
    grid on
    set(gcf,'Color','white');
    hl=light('Position',[-1,0,0]);
    set(gca,'Color','white');
    set(gca,'DataAspectRatio',[1,1,1])
    set(gca,'XLim',XLim,'YLim',YLim,'ZLim',ZLim)
    
    HIn=[];
    PhasePlot=linspace(0,2*pi,150);
    for i=1:length(PhasePlot)
       H=PlotTurbineGeom(T,hf,PhasePlot(i),HIn,Trans,PlotVec,SFVec);
       HIn=H;
       pause(.01);
    end
    
end

**Comment by whophil** [comment]
@Satyamshk2 the `CreateGeom` scripts provided by CACTUS-tools are offered as a convenient way to build simple geometries, but may not cover the use case you need. If `CreateTurbine.m` doesn't allow you to do what you need, you will need to modify it, following the guidance of Section 3.2 of the User Guide.

I am not the author of the `CreateGeom` scripts and it's been a _very long_ time since I looked at any of the `CreateGeom .m` scripts. I took a brief look and I think you do what you want by adding a call to `RotateBlade.m` to rotate each blade about the desired pitch axis.

**Comment by Satyamshk2** [comment]
@whophil Thank you for your suggestion. I will try to modify the geometry this way.

**Comment by jcokemurray** [comment]
Yes, it looks like the basic VAWT generator in CreateTurbine doesn't do
blade twist, but the HAWT generator does. You could follow that example to
add blade twist to a VAWT model...
Jon

**Comment by Satyamshk2** [comment]
@jcokemurray Dear 
I am having some problems validating the CACTUS with VAWT850 Case as per **''Murray, J., and Barone, M., “The Development of CACTUS, a Wind and Marine Turbine Performance Simulation Code,” 49th AIAA Aerospace Sciences Meeting including the New Horizons Forum and Aerospace Exposition, Reston, Virginia: American Institute of Aeronautics and Astronautics, 2011, pp. 1–21.''**
could you please tell me, what was the mount point(eta in CACTUS Code) in the VAWT850 turbine case as it is not available online? 
Thanks and regards
